apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-application-clusterrole
rules:
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications", "sparkapplications/status"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: pm-spark
  name: spark-application-rolebinding
subjects:
- kind: ServiceAccount
  name: pm-airflow
  namespace: pm-airflow
roleRef:
  kind: ClusterRole
  name: spark-application-clusterrole
  apiGroup: rbac.authorization.k8s.io
