apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pm-airflow
  name: spark-application-role
rules:
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications", "sparkapplications/status"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: pm-airflow
  name: spark-application-rolebinding
subjects:
- kind: ServiceAccount
  name: pm-airflow
  namespace: pm-airflow
roleRef:
  kind: Role
  name: spark-application-role
  apiGroup: rbac.authorization.k8s.io
